apiVersion: v1
kind: Service
metadata:
  name: doc-chat-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: doc-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.docChat.containerPort }}
  type: LoadBalancer

