apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertexai-citation-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vertexai-citation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vertexai-citation
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: vertexai-citation
        image: gcr.io/{{ .Values.projectID }}/disearch/vertexai-citations:1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.vertexaiCitation.containerPort }}

