apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-ai-followup-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vertex-ai-followup
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vertex-ai-followup
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: vertex-ai-followup
        image: gcr.io/{{ .Values.projectID }}/disearch/vertexai_followup:1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.vertexAiFollowup.containerPort }}

