apiVersion: v1
kind: Service
metadata:
  name: vertex-ai-followup-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  selector:
    app: vertex-ai-followup
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.vertexAiFollowup.containerPort }}
  type: LoadBalancer

